version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pg_admin
      POSTGRES_PASSWORD: Zt8#5xPqT$kN!3dY
      POSTGRES_DB: malicious_requests
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d



  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
